name: rm_graphql_client
description: A simple command-line application.
environment: 
  sdk: '>=2.8.1 <3.0.0'
dependencies:
  ferry: ^0.9.2
  gql_http_link: ^0.3.2
  uuid: ^2.2.2
dev_dependencies: 
  pedantic: ^1.9.0
  ferry_generator: ^0.3.3
  build_runner: ^1.10.2
